# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6e870c4e-6379-4209-9048-e6f2f927f026";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/99a9da5b-b185-4b56-83dc-86feed246cb5";

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/ca096c41-f3bd-4769-a5a2-ad344edc1bee";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."var".device = "/dev/disk/by-uuid/e005480c-6553-43cc-a48e-750fa0638fcf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4F0A-DA25";
      fsType = "vfat";
    };

  fileSystems."/backup" =
    { device = "/dev/disk/by-uuid/08edeb3f-8672-4318-884f-bc6caf2d3843";
      #device = "/dev/disk/by-id/md-uuid-4307c168:68796337:f89589ca:6cc6dea2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."backup".device = "/dev/disk/by-id/md-uuid-4307c168:68796337:f89589ca:6cc6dea2";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e8720451-9b3b-4132-8851-b5f4b63363ef"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
