# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/29632e24-99cf-4ac0-a265-4db4ff90a361";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/325e7228-4525-4312-b737-4a3f806c2a3f";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6b9d275d-2fd7-4cc0-b3f6-2db3dba66bf9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nix".device = "/dev/disk/by-uuid/92ba7f7b-0ff0-4736-ba61-8c01181c58ee";

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/4132a711-d57e-45e6-80bd-8bb32680724d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."var".device = "/dev/disk/by-uuid/b68f08bf-2de3-45a4-ba11-d1ccaaec120b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E1F0-1ECB";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9558bf5e-9027-4482-8271-60574bc18646";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/6fe427a5-9cff-47db-ba2e-0cb3ecf3e83f";

  fileSystems."/steam1" =
    { device = "/dev/disk/by-uuid/ed075103-5ee8-426e-88ae-18dd2cb8383d";
      fsType = "ext4";
    };

  fileSystems."/steam2" =
    { device = "/dev/disk/by-uuid/23fc1bbc-bba7-4709-a369-6625dcca405b";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a4ee10d8-f3c5-4c05-96d4-d3be94f65332"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
